# -*- coding: utf-8 -*-
#
# ALAMODE documentation build configuration file, created by
# sphinx-quickstart on Wed Jun  4 17:36:19 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
import os
import sys

# Make the pure-Python ``alm`` package importable for autodoc (the API reference
# on the alm_python page) without having to compile/install the wrapper first.
sys.path.insert(0, os.path.abspath("../../python"))

# autodoc only needs the docstrings/signatures of the high-level alm.py, so mock
# the compiled extension (and NumPy, which is only used inside method bodies).
autodoc_mock_imports = ["alm._alm", "numpy"]
autodoc_member_order = "bysource"
autodoc_default_options = {"members": True, "undoc-members": False}

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",  # NumPy-style docstring sections -> field lists (no bogus numbered headings)
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "ALAMODE"
copyright = "2014, Terumasa Tadano"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "2.0"
# The full version, including alpha/beta/rc tags.
release = "2.0.0"

# The language the documentation is built in. The source content is written in
# English; translations live as gettext catalogs under ``locale/<lang>/`` and
# are selected at build time via the ``DOCS_LANGUAGE`` environment variable
# (see docs/Makefile and the docs CI workflow). Untranslated strings fall back
# to the English source automatically.
language = os.environ.get("DOCS_LANGUAGE", "en")

# Where the per-language gettext catalogs (.po/.mo) are kept, relative to this
# directory. ``gettext_compact = False`` keeps one catalog per source file,
# which makes partial translations easier to track and review.
locale_dirs = ["locale/"]
gettext_compact = False

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = "furo"
# html_theme = 'conestack'
html_theme = "breeze"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # ALAMODE has many top-level sections, so keep the whole toctree in the
    # left sidebar. With header_tabs enabled (the breeze default) the
    # top-level entries become header tabs and the sidebar only shows the
    # pages of the current section.
    "header_tabs": False,
}

# Repository info in the html_context convention used by breeze's
# "Edit this page" link (furo instead reads the source_* theme options).
html_context = {
    "github_user": "alamode-code",
    "github_repo": "alamode",
    "github_version": "develop",
    "doc_path": "docs/source",
}

# The canonical base URL of the published site (used for sitemap / <link>).
html_baseurl = "https://alamode-code.github.io/alamode/"

# breeze bundles sphinxext-opengraph, whose generated social-card images use a
# Latin-only font; Japanese titles would render as missing glyphs. Disable the
# card images (the rest of the OpenGraph metadata is kept) for the ja build.
if language == "ja":
    ogp_social_cards = {"enable": False}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "../img/alamode.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Multi-version and multi-language switchers plus a per-language PDF download
# link: small theme-agnostic helpers that read the versions.json (site root)
# and per-version languages.json manifests published by the docs deploy
# workflow, and link to the ALAMODE.pdf published next to each language's HTML.
html_js_files = [
    "version-switcher.js",
    "language-switcher.js",
    "pdf-download.js",
]
html_css_files = [
    "version-switcher.css",
    "language-switcher.css",
    "pdf-download.css",
    "custom.css",
]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%b %d, %Y"

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "ALAMODEdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # 'inputenc': '',
    #
    # Additional stuff for the LaTeX preamble.
    "preamble": """

\\usepackage{bm}
\\usepackage{mathrsfs}
\\usepackage{braket}
""",
}

# The default engine (pdflatex) cannot typeset Japanese, so the Japanese PDF is
# built with LuaLaTeX. Sphinx has no built-in LuaLaTeX+Japanese profile, so the
# few pieces it would otherwise get wrong are configured explicitly here. Latin
# body text keeps Sphinx's default fonts; Japanese glyphs are handled by
# LuaTeX-ja (and its bundled Harano Aji fonts).
if language == "ja":
    latex_engine = "lualatex"
    # Sphinx's default base classes for Japanese (jsbook/jsarticle) are
    # pLaTeX-only and abort under LuaLaTeX; use the LuaTeX-ja counterparts,
    # which load LuaTeX-ja and set up Japanese typesetting on their own.
    latex_docclass = {"manual": "ltjsbook", "howto": "ltjsarticle"}
    # With LuaTeX-ja doing the Japanese typesetting, drop polyglossia/babel:
    # their \setmainlanguage{japanese} demands a CJK-capable *main* font and
    # otherwise aborts the build against the Latin body font set by fontspec.
    latex_elements["polyglossia"] = ""
    latex_elements["babel"] = ""
    # For non-pdflatex engines Sphinx defaults the index builder to xindy, an
    # extra system dependency. The index here is Latin (tag/function names), so
    # use makeindex instead -- it ships with TeX Live (and is what the English
    # pdflatex build already uses), keeping the CI TeX install self-contained.
    latex_use_xindy = False
else:
    # pdflatex only knows the Unicode characters that inputenc declares; a
    # stray math symbol in the prose (as opposed to a :math: role) otherwise
    # aborts the English PDF build. Map the ones that tend to slip in.
    latex_elements["preamble"] += r"""
\DeclareUnicodeCharacter{2212}{\ensuremath{-}}
\DeclareUnicodeCharacter{2264}{\ensuremath{\leq}}
\DeclareUnicodeCharacter{2265}{\ensuremath{\geq}}
\DeclareUnicodeCharacter{2192}{\ensuremath{\rightarrow}}
\DeclareUnicodeCharacter{221E}{\ensuremath{\infty}}
\DeclareUnicodeCharacter{2225}{\ensuremath{\parallel}}
"""

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ("index", "ALAMODE.tex", "ALAMODE Documentation", "Terumasa Tadano", "manual"),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", "alamode", "ALAMODE Documentation", ["Terumasa Tadano"], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "ALAMODE",
        "ALAMODE Documentation",
        "Terumasa Tadano",
        "ALAMODE",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = "ALAMODE"
epub_author = "Terumasa Tadano"
epub_publisher = "Terumasa Tadano"
epub_copyright = "2014, Terumasa Tadano"

# The basename for the epub file. It defaults to the project name.
# epub_basename = u'ALAMODE'

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
# epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
# epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
# epub_identifier = ''

# A unique identification for the text.
# epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
# epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
# epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# The depth of the table of contents in toc.ncx.
# epub_tocdepth = 3

# Allow duplicate toc entries.
# epub_tocdup = True

# Choose between 'default' and 'includehidden'.
# epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
# epub_fix_images = False

# Scale large images.
# epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# epub_show_urls = 'inline'

# If false, no index is generated.
# epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
