.SUFFIXES: .h .cpp
#-----------------------------------------------
# Makefile for the program 'ALM'.
# Please modify the variables properly.
# We recommend to use Intel c++ compiler.
#-----------------------------------------------

# NOTE: These legacy Makefiles are provided for convenience only; the
# CMake build (see the top-level CMakeLists.txt) is the canonical and
# tested way to build ALAMODE. The sources require C++17.
CXX = icpc 
CXXFLAGS = -O2 -xHOST -qopenmp -std=c++17
#CXXFLAGS = -O2 -xHOST -qopenmp -std=c++17 -D_HDF5
INCLUDE = -I../include -I$(HOME)/include -I$(SPGLIB_ROOT)/include
#INCLUDE = -I../include -I$(HOME)/include -I$(SPGLIB_ROOT)/include -I$(HDF5_ROOT)/include

CXXL = ${CXX}
LDFLAGS = -mkl -L$(SPGLIB_ROOT)/lib -lsymspg
#LDFLAGS = -mkl -L$(SPGLIB_ROOT)/lib -lsymspg -L$(HDF5_ROOT)/lib -lhdf5_cpp -lhdf5

LAPACK = 
LIBS = ${LAPACK}

#-----------------------------------------------
# General rules 
#-----------------------------------------------

.cpp.o:
	${CXX} ${CXXFLAGS} ${INCLUDE} -c $<

PROG = alm

vpath %.cpp ../include
CXXSRC= $(wildcard *.cpp) git_commit.cpp

OBJS= ${CXXSRC:.cpp=.o}

default: alm

all: ${PROG}

alm: ${OBJS}
	${CXXL} ${LDFLAGS} -o $@ ${OBJS} ${LIBS}

clean:
	rm -f ${OBJS}

.PHONY: clean

depend:
	gcc -MM *.cpp > .depend

-include .depend
