.SUFFIXES: .h .cpp
#-----------------------------------------------
# Makefile for the program 'ANPHON'.
# Please modify the variables properly.
# We recommend to use Intel c++ compiler.
#-----------------------------------------------

# NOTE: These legacy Makefiles are provided for convenience only; the
# CMake build (see the top-level CMakeLists.txt) is the canonical and
# tested way to build ALAMODE. The sources require C++17.
MPICXX = mpicxx 
#MPICXX = mpiicpc 

# add -D_HDF5 to activate HDF5 support
CXXFLAGS = -O3 -xHOST -qopenmp -std=c++17

# when the HDF5 support is activated, 
# you may need to add -I$(HDF5_ROOT)/include
INCLUDE = -I../include 

LINKER = ${MPICXX}
# when the HDF5 support is activated, 
# you may need to add -L$(HDF5_ROOT)/lib -lhdf5_cpp -lhdf5
LDFLAGS = -mkl 

LAPACK = 
LIBS = ${LAPACK}

#----------------------------------------------
# General rules
#----------------------------------------------

.cpp.o:
	${MPICXX} ${CXXFLAGS} ${INCLUDE} -c $<

PROG = anphon

vpath %.cpp ../include
CXXSRC = $(wildcard *.cpp) git_commit.cpp

OBJS= ${CXXSRC:.cpp=.o}

default: anphon

all: ${PROG}

anphon: ${OBJS}
	${LINKER} ${LDFLAGS} -o $@ ${OBJS} ${LIBS}

clean:
	rm -f ${OBJS}

.PHONY: clean

depend:
	gcc -MM *.cpp > .depend

-include .depend
