.SUFFIXES: .h .cpp
#-----------------------------------------------
# Makefile for the program 'ANPHON'.
# Please modify the variables properly.
# We recommend to use Intel c++ compiler.
#-----------------------------------------------

# MPI version of clang++ with libomp installed via Homebrew
# NOTE: These legacy Makefiles are provided for convenience only; the
# CMake build (see the top-level CMakeLists.txt) is the canonical and
# tested way to build ALAMODE. The sources require C++17.
MPICXX = mpic++
CXXFLAGS = -O3 -std=c++17 -Xpreprocessor -fopenmp
INCLUDE = -I../include -I$(HOME)/include -I/usr/local/opt/boost/include/ -I/usr/local/opt/eigen/include/eigen3/ -I/usr/local/opt/fftw/include/  -I/usr/local/opt/libomp/include/

LINKER = ${MPICXX}

## Mavericks
#LDFLAGS = -framework vecLib
## Yosemite and newer
LDFLAGS = -framework Accelerate

LAPACK = -llapack
LIBS = ${LAPACK} -L/usr/local/lib/ -lfftw3 -L//usr/local/opt/libomp/lib/ -lomp

#----------------------------------------------
# General rules
#----------------------------------------------

.cpp.o:
	${MPICXX} ${CXXFLAGS} ${INCLUDE} -c $<

PROG = anphon

vpath %.cpp ../include
CXXSRC = $(wildcard *.cpp) git_commit.cpp

OBJS= ${CXXSRC:.cpp=.o}

default: anphon

all: ${PROG}

anphon: ${OBJS}
	${LINKER} ${LDFLAGS} -o $@ ${OBJS} ${LIBS}

clean:
	rm -f ${OBJS}

.PHONY: clean

depend:
	gcc -MM *.cpp > .depend

-include .depend
